# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show GITHUB_REF
        run: |
          echo ${GITHUB_REF}
          
      - name: Test regexp
        uses: actions-ecosystem/action-regex-match@v2
        id: tag-number
        with:
          text: github.ref
          regex: '(.*)\/(.*)$'
          
      - name: Print tag number
        if: ${{ steps.tag-number.outputs.group2 == '' }}
        run: |
          exit 1
          
      - name: Fetch release details from thucke/TYPO3.ext.th_rating
        id: get_latest_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/releases/tags/${{ steps.tag-number.outputs.group2 }}
          owner: thucke
          repo: TYPO3.ext.th_rating
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

      #see: https://trstringer.com/github-actions-multiline-strings/
      #substituting the %, \n, and \r characters
      - name: Store release body
        id: set-release-body
        run: |
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"
          echo ::set-output name=release_body::"$RELEASE_BODY"
        env:
          RELEASE_BODY: ${{ fromJson(steps.get_latest_release.outputs.data).body }}

      - name: Print Body variable
        run: |
          echo $release_body
        env:
          release_body: ${{ steps.set-release-body.outputs.release_body}}
          
