# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch releases from th-rating
        id: get_latest_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: thucke
          repo: TYPO3.ext.th_rating
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

      - name: Store release body
        id: set-release-body
        run: |
          RELEASE-BODY="${RELEASE-BODY//'%'/'%25'}"
          RELEASE-BODY="${RELEASE-BODY//$'\n'/'%0A'}"
          RELEASE-BODY="${RELEASE-BODY//$'\r'/'%0D'}"
          echo "::set-output name=release-body::$RELEASE-BODY"
        env:
          RELEASE-BODY: ${{ fromJson(steps.get_latest_release.outputs.data).body }}

      - name: Print Body variable
        run: |
          echo $body
        env:
          body: ${{ steps.set-body.outputs.release-body}}
          
