# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '7.3' ]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show PHP -i
        run: php -i | grep auth
        
      - name: Set  ~/.my.cnf
        run: echo "[mysqld] default_authentication_plugin=mysql_native_password" > ~/.my.cnf
        
      - name: cat  ~/.my.cnf
        run: cat ~/.my.cnf

      - name: Start database server
        run: sudo /etc/init.d/mysql start

      - name: Verify MySQL connection from host
        run: mysql -uroot -proot -e "SHOW DATABASES"
        
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get version
        id: get-version
        run: echo ::set-output name=version::0.4.2
          
      - name: Print tag number
        run: |
          echo ${{ steps.get-version.outputs.version }}
          
      - name: Print repository ${{ github.event.repository.name }}
        run: |
          echo ${{ github.event.repository.name }}
